
blank_issues_enabled: true
contact_links:
  - name: Vehicle Request
    url: https://github.com/someone0002/stellar-feedback/discussions/2
    about: Request vehicles on this thread for the vehicles team to review. Please follow the format!
  - name: Vehicle Issues/Balance
    url: https://github.com/someone0002/stellar-feedback/discussions/3
    about: Let us know if you've found an issue with a vehicle. Make sure it's detailed!
  - name: Feature Request
    url: https://github.com/someone0002/stellar-feedback/discussions/categories/suggestions
    about: Suggest an idea for this project.
  - name: Balance Request
    url: https://github.com/someone0002/stellar-feedback/discussions/categories/balancing
    about: Something doesn't feel quite right? OP almost? Suggest it here.
  - name: Community Feedback
    url: https://github.com/someone0002/stellar-feedback/discussions/categories/ideas
    about: Suggestions and other methods we can improve the community as a collective - be nice!
